DROP DATABASE IF EXISTS dieCuttingOEE;
CREATE DATABASE dieCuttingOEE;

USE dieCuttingOEE;
CREATE TABLE shiftMonthly (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
month1 DECIMAL(2,2) NOT NULL,
month2 DECIMAL(2,2) NOT NULL,
month3 DECIMAL(2,2) NOT NULL,
month4 DECIMAL(2,2) NOT NULL,
month5 DECIMAL(2,2) NOT NULL,
month6 DECIMAL(2,2) NOT NULL,
month7 DECIMAL(2,2) NOT NULL,
month8 DECIMAL(2,2) NOT NULL,
month9 DECIMAL(2,2) NOT NULL,
month10 DECIMAL(2,2) NOT NULL,
month11 DECIMAL(2,2) NOT NULL,
month12 DECIMAL(2,2) NOT NULL,
notes VARCHAR(255),
PRIMARY KEY (id)
);

